<ul>
  <li>Version 1.0 - February 2010
    <ul>
       <li>Initial release with interlinked and experimental google voice gateways.</li>
    </ul>
  </li>
  <li>Version 1.1 - March 2015
    <ul>
       <li>Additional gateways: clickatell, twilio, smsbroadcast.</li>
       <li>Expanded gateway API to support checking for and using extra parameters</li>
       <li>More generous regex for checking message validity</li>
    </ul>
  </li>
</ul>
