<ul>
 <li>CGSMS Version 1.0 - February 2010
  <ul>
   <li>Initial release with Interlinked and experimental Google Voice gateways.</li>
  </ul>
 </li>
 <li>SMSG Version 0.9 - April 2015
  <ul>
   <li>Work-alike replacement for CGSMS</li>
   <li>Gateways: add Clickatell, Twilio, Smsbroadcast, remove defunct Interlinked</li>
   <li>Expanded gateway API supports optional checks for and use of extra parameters</li>
   <li>Enable runtime modifications of gateways' interface by authorised users</li>
   <li>More generous regex for checking message validity</li>
   <li>Better support for later CMSMS versions, bug fixes, UI refinements</li>
  </ul>
 </li>
 <li>Version 0.9.9 - April 2015
  <ul>
   <li>Also support CMSMS 1.12.x</li>
   <li>Implement gateway delivery-report processing, where possible</li>
  </ul>
 </li>
 <li>Version 1.0 - January 2016
  <ul>
   <li>Also support CMSMS 2+</li>
   <li>Encrypt sensitive data</li>
   <li>Abandon pretty-url for delivery reports</li>
   <li>Remove CGExtensions dependency</li>
   <li>Add missing $lang[] members</li>
  </ul>
 </li>
 <li>Version 1.0.1 - February 2016
  <ul>
   <li>https protocol for Clickatell-gateway interactions</li>
  </ul>
 <li>Version 1.1 - September 2016
  <ul>
   <li>renamed classes to fix namespace conflict</li>
   <li>updated Twilio library to v.5.4.1</li>
  </ul>
</ul>
